#!/bin/env bash

APP_NAME=DEFAULT
APP_RUN_COUNT=1
APP_RUN_SLEEP=0
APP_MAIN_TOOLCHAIN=""
TOOLCHAIN_DEFAULT_EXEC=""
TOOLCHAIN_DEFAULT_OPTS=""
TOOLCHAIN_DEFAULT_IS_MANDATORY="1"
TOOLCHAIN_DEFAULT_RC_OK="0"
